#!/usr/bin/env bash

set -o errexit
set -o nounset

# Reference: https://dzone.com/articles/docker-x11-client-via-ssh
chmod o+rw $HOME/.Xauthority
docker run -it \
   --rm \
   --net=host \
   --env=DISPLAY \
   --env=TZ=Spain/Madrid \
   --volume=$HOME:$HOME:rw \
   --volume=$PWD:/media/host:rw \
   --workdir=/media/host \
   --env USER \
   --env USER_ID=`id --user` \
   --env GROUPS=$(groups | xargs getent group | cut -d: -f1,3 | tr '\n' ',' | sed 's|,$||') \
   --name=intellij.$USER \
   jesuspv/intellij "$@"
